# 公共菜单使用独立配置上下文，只加载 SDK 和公共组件，不加载任何产品。
if(DEFINED MODEL OR DEFINED XF_CONFIG_MODEL)
    message(FATAL_ERROR "Common configuration requires its own build directory without MODEL.")
endif()
if(NOT IDF_TARGET MATCHES "^[a-z0-9]+$")
    message(FATAL_ERROR "Common configuration requires an explicit IDF_TARGET.")
endif()

get_filename_component(XF_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(XF_COMMON_CONFIG "${XF_ROOT_DIR}/xf_tool/config/${IDF_TARGET}.conf")
if(NOT EXISTS "${XF_COMMON_CONFIG}")
    message(FATAL_ERROR "Missing common chip configuration: ${XF_COMMON_CONFIG}")
endif()
file(STRINGS "${XF_COMMON_CONFIG}" XF_CONFIG_TARGET REGEX "^[ \t]*CONFIG_IDF_TARGET[ \t]*=")
if(XF_CONFIG_TARGET)
    message(FATAL_ERROR "Remove CONFIG_IDF_TARGET from ${XF_COMMON_CONFIG}; select the chip with CHIP.")
endif()

set(SDKCONFIG_DEFAULTS "${XF_COMMON_CONFIG}")
set(SDKCONFIG "${CMAKE_BINARY_DIR}/sdkconfig")
file(SHA256 "${XF_COMMON_CONFIG}" XF_CONFIG_INPUTS_HASH)
set(XF_CONFIG_INPUTS_STAMP "${CMAKE_BINARY_DIR}/.xf_config_inputs.sha256")
if(EXISTS "${XF_CONFIG_INPUTS_STAMP}" AND EXISTS "${SDKCONFIG}")
    file(READ "${XF_CONFIG_INPUTS_STAMP}" XF_PREVIOUS_CONFIG_HASH)
    if(NOT XF_PREVIOUS_CONFIG_HASH STREQUAL XF_CONFIG_INPUTS_HASH)
        message(STATUS "Common configuration changed; regenerating sdkconfig.")
        configure_file("${SDKCONFIG}" "${SDKCONFIG}.before-conf-change" COPYONLY)
        file(REMOVE "${SDKCONFIG}")
    endif()
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${XF_COMMON_CONFIG}")

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
set(EXTRA_COMPONENT_DIRS "${XF_ROOT_DIR}/xf_common/components")
project("xf_common_config_${IDF_TARGET}")
file(WRITE "${XF_CONFIG_INPUTS_STAMP}" "${XF_CONFIG_INPUTS_HASH}")
